final_project/commons/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from final_project.commons.views import HomePageView, ContactPage, HotelsView, AboutUsView

urlpatterns = [
    path('', HomePageView.as_view(), name='home page'),
    path('hotels/', HotelsView.as_view(), name='show all hotels'),
    path('contact/', ContactPage.as_view(), name='contact page'),
    path('about-us/', AboutUsView.as_view(), name='about use')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('final_project.commons.urls')),
    path('account/', include('final_project.account.urls')),
    path('hotels/', include('final_project.hotels.urls')),
]

final_project/commons/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models

from final_project.account.validators import validate_only_alphabetic
from final_project.hotels.models import Hotels

# Create your models here.

ModelUser = get_user_model()


class Contact(models.Model):
    first_name = models.CharField(
        max_length=30,
        null=False,
        blank=False,
        validators=(
            MinLengthValidator(2, ),
            validate_only_alphabetic,
        )
    )
    email = models.EmailField(
        blank=False,
        null=False,
        unique=True,
    )
    description = models.TextField(
        blank=False,
        null=False,
    )

    class Meta:
        verbose_name = 'Контакти'
        verbose_name_plural = 'Контакти'


class Comments(models.Model):
    description = models.TextField(
        max_length=250,
        blank=False,
        null=False,
    )
    user = models.ForeignKey(
        ModelUser,
        on_delete=models.DO_NOTHING,
    )
    hotel = models.ForeignKey(
        Hotels,
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'Коментари'
        verbose_name_plural = 'Коментари'

final_project/hotels/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse

from final_project.account.models import Profile
from final_project.hotels.validators import hotel_name_validators, location_name_validators, valid_days

# Create your models here.
User = get_user_model()


class Hotels(models.Model):
    hotel_name = models.CharField(
        max_length=30,
        null=False,
        blank=False,
        unique=True,
        validators=(
            hotel_name_validators,
        )
    )
    location = models.CharField(
        max_length=30,
        null=False,
        blank=False,
        validators=(
            location_name_validators,
        )
    )

    description = models.TextField(
        null=False,
        blank=False,
    )
    price = models.FloatField(
        null=False,
        blank=False,
    )

    stars = models.IntegerField(
        null=False,
        blank=False,
        validators=(
            MinValueValidator(1, ),
            MaxValueValidator(5, ),
        )
    )
    hotel_picture = models.ImageField(
        null=False,
        blank=False,
        upload_to='images/hotels/',
    )
    created_by_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="Hotel",
        null=True,
    )
    reserve_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = 'Хотели'
        verbose_name_plural = 'Хотели'

    def __str__(self):
        return self.hotel_name


class ReservationModel(models.Model):
    CHOICES = (
        ('All inclusive', 'All inclusive'),
        ('Not all inclusive', 'Not all inclusive'),
    )

    days = models.PositiveIntegerField(
        null=False,
        blank=False,
        validators=(
            valid_days,
        )
    )

    choices = models.CharField(
        max_length=20,
        choices=CHOICES,
        null=False,
        blank=False,
    )
    total_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
    )
    attached_user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="reservation",
        null=True,
        blank=True,
    )
    attached_hotel = models.ForeignKey(
        Hotels,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = 'Резервации'
        verbose_name_plural = 'Резервации'

    def __str__(self):
        return f"{self.choices} {self.attached_user}"

    def get_absolute_url(self):
        return reverse('user reservation', args=[str(self.pk)])

final_project/commons/forms.py
from django import forms

from final_project.commons.models import Contact, Comments
from django.utils.translation import gettext_lazy as _


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        label=_('Имe'),
        widget=forms.TextInput(
            attrs={'placeholder': 'Въведете имe'}
        )
    )
    email = forms.EmailField(
        label=_('Имейл'),
        widget=forms.EmailInput(
            attrs={'placeholder': 'Въведете имейл'}
        )
    )
    description = forms.CharField(
        label=_('Описание'),
        widget=forms.Textarea(
            attrs={'placeholder': 'Въведете вашите въпроси:'}
        )
    )

    class Meta:
        model = Contact
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('description',)

final_project/hotels/forms.py
from django import forms

from final_project.hotels.models import Hotels, ReservationModel


# class MultipleImageField(forms.ImageField):
#     def to_python(self, data):
#         if isinstance(data, list):
#             return [super().to_python(item) for item in data]
#         return super().to_python(data)


class HotelForm(forms.ModelForm):
    hotel_name = forms.CharField(
        label='Име на Хотела',
        widget=forms.TextInput(
            attrs={'placeholder': 'Въведете името на хотела'}
        )
    )
    location = forms.CharField(
        label='Локация',
        widget=forms.TextInput(
            attrs={'placeholder': 'Въведете локацията'}
        )
    )
    description = forms.CharField(
        label='Описание',
        widget=forms.Textarea(
            attrs={'placeholder': 'Въведете описание'}
        )
    )
    price = forms.CharField(
        label='Цена',
        widget=forms.TextInput(
            attrs={'placeholder': 'Въведете цена за стая за 1 ден'}
        )
    )
    stars = forms.CharField(
        label="Звези на хотела",
        widget=forms.NumberInput(
            attrs={'placeholder': 'Въведете звездите на хотела  (1-5)'}
        )
    )
    hotel_picture = forms.ImageField(
        label='Снимка'
    )

    class Meta:
        model = Hotels
        exclude = ('attached_user', 'reserve_by', 'created_by_user')


class ReservationForm(forms.ModelForm):
    total_price = forms.DecimalField(
        label='',
        widget=forms.NumberInput(
            attrs={'hidden': True, }
        )
    )
    days = forms.IntegerField(
        label='Дни',
        widget=forms.NumberInput(
            attrs={'placeholder': "Въведете нощувки"}
        )
    )

    class Meta:
        model = ReservationModel
        exclude = ('attached_user', 'attached_hotel',)
        labels = {
            'choices': 'Избор'
        }


class EditHotelForm(forms.ModelForm):
    class Meta:
        model = Hotels
        fields = ('hotel_name', 'location', 'description', 'price', 'stars', 'hotel_picture')
        labels = {
            'hotel_name': 'Име на хотела',
            'location': 'Локация',
            'description': 'Описание',
            'price': 'Цена за нощувка',
            'stars': 'Звезди',
            'hotel_picture': 'Снимка на хотела'
        }

final_project/commons/views.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from final_project.commons.forms import ContactForm
from final_project.hotels.models import Hotels


# Create your views here.
class HotelsView(ListView):
    template_name = 'hotels/all-hotels.html'
    model = Hotels


class HomePageView(auth_views.TemplateView):
    template_name = 'common/home-page.html'


class AboutUsView(auth_views.TemplateView):
    template_name = 'common/about-us.html'


class ContactPage(CreateView):
    form_class = ContactForm
    template_name = 'common/contacts.html'
    success_url = reverse_lazy('home page')

templates/common/about-us.html
{% extends 'base-template.html' %}
{% block page_content %}
    <main class="about-us">
        <h2>За нас</h2>
        <p>Ние сме водещата компания в областта на резервациите и настаняването. Нашата цел е да предоставим на
            клиентите безпроблемни и удобни услуги за резервации, които отговарят на техните нужди и предпочитания.</p>
        <p>С нас можете да откриете най-добрите обекти за настаняване във всяка дестинация. Разполагаме с голям каталог
            от хотели, вили, апартаменти и други видове настаняване, които могат да задоволят различни бюджети и
            предпочитания.</p>
        <p>Екипът ни се гордее с висококачественото обслужване и персонално внимание към всеки клиент. Нашата мисия е да
            направим вашия престой незабравим и приятен.</p>
    </main>

{% endblock %}

templates/common/contacts.html
{% extends 'base-template.html' %}
{% block page_content %}

    <div class="form">
        <h2>Свържете се с нас</h2>
        <p>Ако имате въпроси или нужда от допълнителна информация, моля, попълнете формата по-долу и ние ще се свържем с
            вас възможно най-скоро.</p>

        <form class="register-form" method="post" action="{% url 'contact page' %}">
            {{ form }}
            {% csrf_token %}
            <button type="submit">Изпрати</button>

        </form>
    </div>
{% endblock %}

templates/common/home-page.html
{% extends 'base-template.html' %}
{% block page_content %}
    <!-- Home page -->
    <!-- Съдържание на началната страница -->
    <div class="header">
    <h2>Stay HUB</h2>
    <p>Добре дошли в StayHUB, вашата крайна дестинация за безпроблемни резервации и изключителни хотелски
        изживявания. В StayHub разбираме важността на намирането на перфектното настаняване, което отговаря на
        вашите специфични нужди и предпочитания.</p>

    <div class="nav-bar-two">
        {% if not request.user.is_authenticated %}
            <a href="{% url 'sign in' %}" class="button">Вход</a>
            <a href="{% url 'show all hotels' %}" class="button">Хотели</a>
            <a href="{% url 'sign on' %}" class="button">Регистрация</a>
        {% else %}
            <h4>Защо да изберете StayHUB?</h4>
            <ul>
                <li>Голямо разнообразие от хотели,</li>
                <li>Лесно и бързо търсене на настаняване,</li>
                <li>Отзиви и оценки от други гости,</li>
                <li>Ексклузивни промоции и специални оферти,</li>
                <li>24/7 клиентска поддръжка</li>
            </ul>
            <p>StayHUB ви предоставя богат избор от хотели. Независимо дали търсите романтична почивка на
                плажа,
                разкошен градски хотел или спокойно затънтени в планините, ние имаме всичко, от което се нуждаете.
                Открийте
                уникални места за настаняване и създайте незабравимо пътешествие с StayHUB.</p>
        {% endif %}
    </div>
{% endblock %}

templates/common/reservation.html
{% extends 'base-template.html' %}
{% block page_content %}

    <section id="hotel-details">
        <h1>Резервирай: {{ hotel.hotel_name }}</h1>
        <div class="info-section">
            <div class="hotel-header">
                <img class="hotel-img"
                     src="{{ hotel.hotel_picture.url }}"
                     alt='hotel image'/>
                <h1>Име: {{ hotel.hotel_name }}<span class="stars">Звезди: {{ hotel.stars }}</span></h1>

                <p><span class="type">Локация: {{ hotel.location }}</span></p>

                <p><span class="type">Цена на нощувка: {{ hotel.price|floatformat:2 }}лв</span></p>
            </div>
            <p class="text">
            {{ hotel.description }}
            <form class="register-form" method="post" action="{% url 'reservation' pk=hotel.pk %}">
                {{ form.as_p }}
                {% csrf_token %}
                <h1>Финална цена: <span id="final-price"></span></h1>

                <script>
                    document.addEventListener('DOMContentLoaded', () => {
                        const daysInput = document.querySelector('#id_days');
                        const choicesInput = document.querySelector('#id_choices');
                        const finalPriceElement = document.querySelector('#final-price');
                        const totalPriceInput = document.querySelector('#id_total_price');

                        const hotelPrice = parseFloat('{{ hotel.price }}');

                        const updateFinalPrice = () => {
                            const days = parseInt(daysInput.value, 10);
                            const choice = choicesInput.value;
                            let finalPrice = 0;
                            if (days && choice === 'All inclusive') {
                                finalPrice = hotelPrice * days * 1.2;
                            } else if (days) {
                                finalPrice = hotelPrice * days;
                            }

                            finalPriceElement.textContent = finalPrice.toFixed(2);
                            totalPriceInput.value = finalPrice.toFixed(2);
                        };

                        daysInput.addEventListener('input', updateFinalPrice);
                        choicesInput.addEventListener('change', updateFinalPrice);
                        updateFinalPrice();
                    });
                </script>
                <button class="button" type="submit">Резервирай</button>
            </form>
            </p>

            <div class="buttons">
                <a href="{% url 'show all hotels' %}" class="button">Хотели</a>
            </div>

        </div>
    </section>



{% endblock %}